"""empty message

Revision ID: 70a3612f476d
Revises: ec02f7236a4e
Create Date: 2024-03-20 17:04:04.278344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a3612f476d'
down_revision = 'ec02f7236a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    modules_table = sa.Table('modules', sa.MetaData(), autoload_with=op.get_bind())

    op.execute(
        modules_table.update().where(modules_table.c.code == 'IY4103').values(description = "Website development covering interesting topics such as Flask, MVC, Bootstrap and JavaScript")
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
